import Head from 'next/head';
import Typography from '../components/Typography';

export default function Home() {
  return (
    <div className='max-w-full'>
      <Head>
        <title>Twind Typography Lab</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='max-w-3xl mx-auto mt-10'>
        <div className='max-w-7xl'>
          <Typography size='5xl' color='purple' className='mb-10' />
          <Typography size='sm' color='red' />
          <Typography size='md' color='blue' />
          <Typography size='lg' color='purple' />
          <Typography size='xl' color='green' />
          <Typography size='2xl' color='indigo' />
          <Typography size='3xl' color='orange' />
          <Typography size='4xl' color='green' />
        </div>
      </main>
    </div>
  );
}
