import Head from 'next/head';
import Button from '../components/Buttons';

export default function Home() {
  return (
    <div className='max-w-full'>
      <Head>
        <title>Twind Lab</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='max-w-3xl mx-auto mt-10'>
        <div className='max-w-7xl'>
          <h1 className='text-5xl font-bold ml-2 mb-10'>Buttons</h1>
          <Button variant='purple' />
          <Button variant='red' />
          <Button variant='blue' />
          <Button variant='purple' />
          <Button variant='green' />
          <Button variant='indigo' />
          <Button variant='orange' />
          <Button variant='green' />
        </div>
      </main>
    </div>
  );
}
